export declare enum Status {
    VERIFYING = "verifying",
    OPEN = "open",
    CLOSED = "closed",
    CREATED = "created",
    PENDING = "pending",
    PAYING = "paying",
    NOT_PAID = "notPaid",
    PLACED = "placed",
    APPROVED = "approved",
    DECLINED = "declined",
    POSTED = "posted",
    RECEIVED = "received",
    DISPUTED = "disputed",
    NOT_RECEIVED = "notReceived",
    NO_RESPONSE = "noResponse",
    RESOLVED = "resolved",
    REFUNDED = "refunded",
    COMPLETE = "complete",
    CANCELLED = "cancelled"
}
